name: Run-Every-5-Minutes

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print some hell
        run: |
          date -u +"UTC: %Y-%m-%d %H:%M:%S"
          echo "Hell-2-THE-WORLD!"
