---
name: Run-Every-60s

on:
  workflow_dispatch: {}

concurrency:
  group: run-every-60s
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Main task
        run: |
          echo "Run at: $(date -u)"
          echo "Hello scheduler"

      - name: ALWAYS trigger next run (even if previous step fails)
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          BASE="https://api.github.com/repos/$REPO/actions/workflows"
          WF="run-every-60s.yml/dispatches"

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            "$BASE/$WF" \
            -d '{"ref":"master"}'
