---
name: Run-Every-60-Seconds

on:
  workflow_dispatch: {}

concurrency:
  group: run-every-60s
  cancel-in-progress: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Main task
        run: |
          NOW=$(date +%s)
          echo "Current time: $NOW"
          echo "Hello from 60s scheduler"

          echo $NOW > last_run.txt

      - name: Trigger next run
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          BASE="https://api.github.com/repos/$REPO/actions/workflows"
          WORKFLOW="run-every-60-seconds.yml/dispatches"

          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            "$BASE/$WORKFLOW" \
            -d '{"ref":"master"}'
